spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/fluxchat
    username: fluxchat
    password: fluxchat
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/fluxchat
    user: fluxchat
    password: fluxchat
    locations: classpath:db/migration
    schemas: public
  sql:
    init:
      mode: never
  mongodb:
    uri: mongodb://localhost:27017/fluxchat
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

jwt:
  secret_key: flux-chat-secret-key-must-be-at-least-256-bits-long-enough
  access-expiration-minutes: 15
  refresh-expiration-days: 14