spring:
  # H2 (R2DBC)
  r2dbc:
    url: r2dbc:h2:mem:///fluxchat
    username: sa
    password:
  sql:
    init:
      mode: always

  # MongoDB
  mongodb:
    uri: mongodb://localhost:27017/fluxchat

    # Redis
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

jwt:
  secret_key: flux-chat-secret-key-must-be-at-least-256-bits-long-enough
  access-expiration-minutes: 15
  refresh-expiration-days: 14